### PR TITLE
Update CNAME

### PR DESCRIPTION
**Pull request by hax4dazy**

### CODE REVIEW

**Comment by hax4dazy** [comment]
OH COCK THIS IS DOING THAT

**Comment by friedkeenan** [comment]
cock

**Comment by hax4dazy** [comment]
Don't mind me i'm being an idoit

**Comment by noahc3** [comment]
:clap:

**Comment by TechGeekGamer** [comment]
@hax4dazy stop being idoit :harold:

**Comment by hax4dazy** [comment]
Its late ok :sadcat:

**Pull request closed without merging**
